// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onEmergenciafisicoChange();
void onReset1Change();
void onReset2Change();

float sensorValueA0;
float voltageA0;
float voltageA1;
CloudLight emergenciafisico;
CloudLight m1status;
CloudLight m2status;
CloudLight manutencao1;
CloudLight manutencao2;
CloudLight reset1;
CloudLight reset2;
int contador;
int contador2;
int contador3;
int contador4;
int motor1luz;
int motor2luz;
CloudLocation localizacao;

void initProperties(){

  ArduinoCloud.addProperty(sensorValueA0, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(voltageA0, READ, 5 * SECONDS, NULL);
  ArduinoCloud.addProperty(voltageA1, READ, 5 * SECONDS, NULL);
  ArduinoCloud.addProperty(emergenciafisico, READWRITE, ON_CHANGE, onEmergenciafisicoChange);
  ArduinoCloud.addProperty(m1status, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(m2status, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(manutencao1, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(manutencao2, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(reset1, READWRITE, ON_CHANGE, onReset1Change);
  ArduinoCloud.addProperty(reset2, READWRITE, ON_CHANGE, onReset2Change);
  ArduinoCloud.addProperty(contador, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(contador2, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(contador3, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(contador4, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(motor1luz, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(motor2luz, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(localizacao, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
